#!name=城市通小程序
#!desc=城市通小程序自动签到（获取Token + 定时任务）
#!author=Sliverkiss
#!homepage=https://gist.github.com/Sliverkiss

[MITM]
hostname = %APPEND% wxxcx.17u.cn

[Script]
# 获取 Token（打开微信小程序 -> 城市通 -> 我的）
城市通获取Token = type=http-response,pattern=^https:\/\/wxxcx\.17u\.cn\/subwayapi\/user\/detail,requires-body=true,timeout=60,script-path=https://gist.githubusercontent.com/Sliverkiss/74ce859af0cd8a602b00bf5efdfddb53/raw/cst.js

# 每天09:00执行签到
城市通签到 = type=cron,cronexp=0 9 * * *,timeout=60,script-path=https://gist.githubusercontent.com/Sliverkiss/74ce859af0cd8a602b00bf5efdfddb53/raw/cst.js
